package net.senx.ircactions.dadjokes;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

public class DadJokesManager
{
    private static List<String> jokes = new ArrayList<>();

    static
    {
        // All Jokes From -> https://www.countryliving.com/life/a27452412/best-dad-jokes/
        jokes.add("I'm afraid for the calendar. Its days are numbered.");
        jokes.add("My wife said I should do lunges to stay in shape. That would be a big step forward.");
        jokes.add("Why do fathers take an extra pair of socks when they go golfing? In case they get a hole in one!");
        jokes.add("Singing in the shower is fun until you get soap in your mouth. Then it's a soap opera.");
        jokes.add("What do a tick and the Eiffel Tower have in common? They're both Paris sites.");
        jokes.add("What do you call a fish wearing a bowtie?....... Sofishticated.");
        jokes.add("How do you follow Will Smith in the snow? You follow the fresh prints.");
        jokes.add("If April showers bring May flowers, what do May flowers bring? Pilgrims.");
        jokes.add("I thought the dryer was shrinking my clothes. Turns out it was the refrigerator all along.");
        jokes.add("How does dry skin affect you at work? You don’t have any elbow grease to put into it.");
        jokes.add("What do you call a factory that makes okay products? A satisfactory.");
        jokes.add("Dear Math, grow up and solve your own problems.");
        jokes.add("What did the janitor say when he jumped out of the closet?.... Supplies!");
        jokes.add("Have you heard about the chocolate record player? It sounds pretty sweet.");
        jokes.add("What did the ocean say to the beach? Nothing, it just waved.");
        jokes.add("Why do seagulls fly over the ocean? Because if they flew over the bay, we'd call them bagels.");
        jokes.add("I only know 25 letters of the alphabet. I don't know y.");
        jokes.add("How does the moon cut his hair? Eclipse it.");
        jokes.add("What did one wall say to the other? I'll meet you at the corner.");
        jokes.add("What did the zero say to the eight? That belt looks good on you.");
        jokes.add("A skeleton walks into a bar and says, 'Hey, bartender. I'll have one beer and a mop.");
        jokes.add("Where do fruits go on vacation? Pear-is!");
        jokes.add("I asked my dog what's two minus two. He said nothing.");
        jokes.add("What did Baby Corn say to Mama Corn? Where's Pop Corn?");
        jokes.add("What's the best thing about Switzerland? I don't know, but the flag is a big plus.");
        jokes.add("What does a sprinter eat before a race? Nothing, they fast!");
        jokes.add("Where do you learn to make a banana split? Sundae school.");
        jokes.add("What has more letters than the alphabet? The post office!");
        jokes.add("Dad, did you get a haircut? No, I got them all cut!");
        jokes.add("What do you call a poor Santa Claus? St. Nickel-less.");
        jokes.add("I got carded at a liquor store, and my Blockbuster card accidentally fell out. The cashier said never mind.");
        jokes.add("Where do boats go when they're sick? To the boat doc.");
        jokes.add("I don't trust those trees. They seem kind of shady.");
        jokes.add("My wife is really mad at the fact that I have no sense of direction. So I packed up my stuff and right!");
        jokes.add("How do you get a squirrel to like you? Act like a nut.");
        jokes.add("Why don't eggs tell jokes? They'd crack each other up.");
        jokes.add("I don't trust stairs. They're always up to something.");
        jokes.add("What do you call someone with no body and no nose? Nobody knows.");
        jokes.add("Did you hear the rumor about butter? Well, I'm not going to spread it!");
        jokes.add("Why couldn't the bicycle stand up by itself? It was two tired.");
        jokes.add("What did one hat say to the other?\" \"Stay here! I'm going on ahead.");
        jokes.add("Why did Billy get fired from the banana factory? He kept throwing away the bent ones.");
        jokes.add("Dad, can you put my shoes on? No, I don't think they'll fit me.");
        jokes.add("Why can't a nose be 12 inches long? Because then it would be a foot.");
        jokes.add("What does a lemon say when it answers the phone? Yellow!");
        jokes.add("This graveyard looks overcrowded. People must be dying to get in.");
        jokes.add("What kind of car does an egg drive? A yolkswagen.");
        jokes.add("Dad, can you put the cat out? I didn't know it was on fire.");
        jokes.add("How do you make 7 even? Take away the s.");
        jokes.add("How does a taco say grace? Lettuce pray.");
        jokes.add("What time did the man go to the dentist? Tooth hurt-y.");
        jokes.add("Why didn't the skeleton climb the mountain? It didn't have the guts.");
        jokes.add("What do you call it when a snowman throws a tantrum? A meltdown.");
        jokes.add("How many tickles does it take to make an octopus laugh? Ten tickles.");
        jokes.add("I have a joke about chemistry, but I don't think it will get a reaction.");
        jokes.add("What concert costs just 45 cents? 50 Cent featuring Nickelback!");
        jokes.add("What does a bee use to brush its hair? A honeycomb!");
        jokes.add("How do you make a tissue dance? You put a little boogie in it.");
        jokes.add("Why did the math book look so sad? Because of all of its problems!");
        jokes.add("What do you call cheese that isn't yours? Nacho cheese.");
        jokes.add("My dad told me a joke about boxing. I guess I missed the punch line.");
        jokes.add("What kind of shoes do ninjas wear? Sneakers!");
        jokes.add("How does a penguin build its house? Igloos it together.");
        jokes.add("How did Harry Potter get down the hill?\" \"Walking. JK! Rowling.");
        jokes.add("I used to be addicted to soap, but I'm clean now.");
        jokes.add("A guy walks into a bar... and he was disqualified from the limbo contest.");
        jokes.add("You think swimming with sharks is expensive? Swimming with sharks cost me an arm and a leg.");
        jokes.add("When two vegans get in an argument, is it still called a beef?");
        jokes.add("I ordered a chicken and an egg from Amazon. I'll let you know...");
        jokes.add("Do you wanna box for your leftovers? No, but I'll wrestle you for them.");
        jokes.add("That car looks nice but the muffler seems exhausted.");
        jokes.add("Shout out to my fingers. I can count on all of them.");
        jokes.add("If a child refuses to nap, are they guilty of resisting a rest?");
        jokes.add("What country's capital is growing the fastest? Ireland. Every day it's Dublin.");
        jokes.add("I once had a dream I was floating in an ocean of orange soda. It was more of a fanta sea.");
        jokes.add("Did you know corduroy pillows are in style? They're making headlines.");
        jokes.add("Did you hear about the kidnapping at school? It's okay, he woke up.");
        jokes.add("A cheeseburger walks into a bar. The bartender says, 'Sorry, we don't serve food here.'");
        jokes.add("I once got fired from a canned juice company. Apparently I couldn't concentrate.");
        jokes.add("I used to play piano by ear. Now I use my hands.");
        jokes.add("Have you ever tried to catch a fog? I tried yesterday but I mist.");
        jokes.add("I'm on a seafood diet. I see food and I eat it.");
        jokes.add("Why did the scarecrow win an award? Because he was outstanding in his field.");
        jokes.add("I made a pencil with two erasers. It was pointless.");
        jokes.add("How do you make a Kleenex dance? Put a little boogie in it!");
        jokes.add("I'm reading a book about anti-gravity. It's impossible to put down!");
        jokes.add("Did you hear about the guy who invented the knock-knock joke? He won the 'no-bell' prize.");
        jokes.add("I've got a great joke about construction, but I'm still working on it.");
        jokes.add("I used to hate facial hair...but then it grew on me.");
        jokes.add("I decided to sell my vacuum cleaner—it was just gathering dust!");
        jokes.add("I had a neck brace fitted years ago and I've never looked back since.");
        jokes.add("You know, people say they pick their nose, but I feel like I was just born with mine.");
        jokes.add("What's brown and sticky? A stick.");
        jokes.add("Why can't you hear a psychiatrist using the bathroom? Because the 'P' is silent.");
        jokes.add("What do you call an elephant that doesn't matter? An irrelephant.");
        jokes.add("What do you get from a pampered cow? Spoiled milk.");
        jokes.add("I like telling Dad jokes. Sometimes he laughs!");
        jokes.add("What's the best smelling insect? A deodor-ant.");
        jokes.add("I used to be a personal trainer. Then I gave my too weak notice.");
        jokes.add("Did I tell you the time I fell in love during a backflip? I was heels over head!");
        jokes.add("If a child refuses to sleep during nap time, are they guilty of resisting a rest?");
        jokes.add("I ordered a chicken and an egg online. I’ll let you know.");
        jokes.add("It takes guts to be an organ donor.");
        jokes.add("If you see a crime at an Apple Store, does that make you an iWitness?");
        jokes.add("I'm so good at sleeping, I can do it with my eyes closed!");
        jokes.add("I was going to tell a time-traveling joke, but you guys didn't like it.");
        jokes.add("What did the vet say to the cat? How are you feline?");
        jokes.add("What do you call a lazy baby kangaroo? A pouch potato!");
        jokes.add("What happens when M&M’s can’t agree on anything? They reach an M-passe.");
        jokes.add("What do you call a fake noodle? An impasta.");
        jokes.add("What do you call a belt made of watches? A waist of time.");
        jokes.add("What happens when a strawberry gets run over crossing the street? Traffic jam.");
        jokes.add("What do you call two monkeys that share an Amazon account? Prime mates.");
        jokes.add("What do you call a pony with a sore throat? A little hoarse.");
        jokes.add("Where do math teachers go on vacation? Times Square.");
        jokes.add("Whenever I try to eat healthy, a chocolate bar looks at me and Snickers.");
        jokes.add("What does garlic do when it gets hot? It takes its cloves off.");
        jokes.add("What's a robot's favorite snack? Computer chips.");
        jokes.add("How much does it cost Santa to park his sleigh?\" \"Nothing, it's on the house.");
        jokes.add("Mountains aren't just funny. They're hill areas.");
        jokes.add("What do clouds wear? Thunderwear.");
        jokes.add("Why are piggy banks so wise? They're filled with common cents.");
        jokes.add("Why is Peter Pan always flying? He neverlands.");
        jokes.add("How do you get a good price on a sled? You have toboggan.");
        jokes.add("How can you tell if a tree is a dogwood tree? By its bark.");
        jokes.add("I used to hate facial hair, but then it grew on me.");
        jokes.add("It's inappropriate to make a 'dad joke' if you're not a dad. It's a faux pa.");
        jokes.add("What do you call a hot dog on wheels? Fast food!");
        jokes.add("Where do young trees go to learn? Elementree school.");
        jokes.add("Did you hear about the circus fire? It was in tents.");
        jokes.add("Can February March? No, but April May!");
        jokes.add("How do lawyers say goodbye? We'll be suing ya!");
        jokes.add("Wanna hear a joke about paper? Never mind—it's tearable.");
        jokes.add("What's the best way to watch a fly fishing tournament? Live stream.");
        jokes.add("Spring is here! I got so excited I wet my plants.");
        jokes.add("I could tell a joke about pizza, but it's a little cheesy.");
        jokes.add("Don't trust atoms. They make up everything!");
        jokes.add("When does a joke become a dad joke? When it becomes apparent.");
        jokes.add("I wouldn't buy anything with velcro. It's a total rip-off.");
        jokes.add("What’s an astronaut’s favorite part of a computer? The space bar.");
        jokes.add("I don't play soccer because I enjoy the sport. I'm just doing it for kicks!");
        jokes.add("Why are elevator jokes so classic and good? They work on many levels.");
        jokes.add("Why do bees have sticky hair? Because they use a honeycomb.");
        jokes.add("Which state has the most streets? Rhode Island.");
        jokes.add("What did the coffee report to the police? A mugging.");
        jokes.add("What did the fish say when he hit the wall? Dam.");
        jokes.add("Is this pool safe for diving? It deep ends.");
        jokes.add("If you see a crime happen at the Apple store, what does it make you? An iWitness.");
        jokes.add("I once submitted 10 puns to a joke competition. I really thought with that many, one was sure to be a winner. Sadly, no pun in ten did.");
        jokes.add("I tried to make up a joke about ghost but I couldn't. It had plenty of spirit but no body.");
        jokes.add("Today at the bank, an old lady asked me to check her balance... So I pushed her over.");
        jokes.add("I once got fired from a canned juice factory.  Apparently i couldn't concentrate.");
        jokes.add("I was walking down the beach when i heard a swimmer yelling for help with a shark circling him. I just laughed....I knew that shark wasn't going to help him.");
        jokes.add("How many storm troopers does it take to change a light-bulb? None. Because they are all on the dark side.");
    }

    public static String GetRandomJoke()
    {
        Random random = new Random();
        int index = random.nextInt(jokes.size());
        return jokes.get(index);
    }
}
